### ISSUE TITLE
Issue with installing Damage Report v3.31

### ISSUE THREAD

**Issue by scott400k** [DorianTheGrey/DU-DamageReport#20]
I have been using an older build of Damage Report but have recently updated to V3.31 this works fine until I try to edit the parameters and then anything I change, then save seems to cause the programming board to throw an error.

I have tried to copy this from the conf file in GitHub using the raw page as described and saving the file locally and then opening in notepad to copy out (this gives an error that LUA script has no exported variable when trying to edit the parameters)
  
![image](https://user-images.githubusercontent.com/71563508/129421533-74832185-9288-4ae7-9452-16bc321cc357.png)

**Comment by cbrfromhell** [comment]
I too am having this issue, even using the quotation marks if I remove what's in field X to name the ship it breaks the script.

**Comment by DorianTheGrey** [comment]
Hi guys,

thanks for contacting. Please see the Installation instruction on the main page, it says: "Rightclick on your programming board -> advanced -> edit lua parameters. Here you can enter the name of your ship. Do not remove the quotation marks." Meaning: you can not remove the quotation marks for the ship name, you have to enter your name within quotation marks.

This is not a bug in the script, it's a limitation in the DU-LUA. If you leave the quotation marks, the script will break, you need to remove the database and programming board, wipe both, replace them and install the script again. Sorry, there's nothing I can do, and NQ has a ticket for it since a very long time.

**Comment by scott400k** [comment]
This is not closed @DorianTheGrey the issue is multiple in that the "ship name" field should say ship name and its just says X (as per my other installations), Also if ANY skill parameter is edited the script breaks.
